### ISSUE TITLE
Compile errors for ESP32C3

### ISSUE THREAD

**Issue by rpatel3001** [FastLED/FastLED#1351]
Trying to use this library as fastled_clockless in esphome for an ESP32C3, using the following config:

```
esphome:
  name: test
  platformio_options:
    board_build.mcu: esp32c3
    platform_packages:
      - platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.2

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino
    version: 2.0.2
    platform_version: https://github.com/tasmota/platform-espressif32/releases/download/v2.0.2idf/platform-espressif32-2.0.2.zip
```

 The build reports that it's using FastLED 3.3.2. I get several compile errors similar to the following:

```
.piolibdeps/ir-env-1/FastLED/platforms/esp/32/fastpin_esp32.h:16:17: error: 'gpio_dev_t' {aka 'volatile struct gpio_dev_s'} has no member named 'out1_w1ts'; did you mean 'out_w1ts'?
```

```
.piolibdeps/ir-env-1/FastLED/platforms/esp/32/fastpin_esp32.h:32:31: error: no match for 'operator^=' (operand types are 'volatile gpio_dev_s::<unnamed union>' and 'long unsigned int')
```

```
/piolibs/FastLED/noise.cpp:593:100: error: ambiguous overload for 'operator*' (operand types are 'q44' {aka 'q<unsigned char, 4, 4>'} and 'int')
```

I managed to get it to build by replacing all instances of `out1` with `out` and adding .val to out* anywhere it isn't already in fastpin_esp32.h, and removing the two #ifdef FASTLED_ARM directives in lib8tion.h but I'm not in a position to review the effects of the change and open a PR, just posting as an FYI.
